# Symphony by vyrx
# Theme: Vague
# https://github.com/vyrx-dev

add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

palette = "colors"

[palettes.colors]
mustard = '#f3be7c' # vague yellow
color1 = '#aeaed1'  # vague cyan (primary)
color2 = '#252530'  # vague black
color3 = '#cdcdcd'  # vague foreground
color4 = '#252530'  # vague black
color5 = '#252530'  # vague black
color6 = '#121314'  # vague background
color7 = '#121314'  # vague background
color8 = '#aeaed1'  # vague cyan
color9 = '#6e94b2'  # vague blue

[directory]
style = "fg:#aeaed1 bold" # vague cyan
read_only = " 󰌾"
read_only_style = "fg:#d8647e" # vague red
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:#aeaed1 bold)'
error_symbol = '[❯](fg:#e08398 bold)'
vicmd_symbol = '[❮](fg:#121314 bold)'

[git_branch]
style = "fg:#6e94b2 bold" # vague blue
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#d8647e)]($style)'
# style = "bg:#394260"

[os]
format = "[$symbol]($style)"
style = "fg:#aeaed1 bold" # vague cyan
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#ea6962 )]($style)'
# time_format = "%R"

[line_break]
disabled = true

