# Symphony by vyrx
# Theme: Gruvbox Material
# https://github.com/vyrx-dev

add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

palette = "colors"

[palettes.colors]
mustard = '#d8a657' # gruvbox yellow
color1 = '#7daea3'  # gruvbox blue (primary)
color2 = '#32302f'  # gruvbox gray
color3 = '#ddc7a1'  # gruvbox foreground
color4 = '#32302f'  # gruvbox gray
color5 = '#32302f'  # gruvbox gray
color6 = '#111313'  # gruvbox background
color7 = '#111313'  # gruvbox background
color8 = '#7daea3'  # gruvbox blue
color9 = '#89b482'  # gruvbox cyan

[directory]
style = "fg:#7daea3 bold" # gruvbox blue (matches OS)
read_only = " 󰌾"
read_only_style = "fg:#ea6962" # gruvbox red
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:#d8a657 bold)' # gruvbox yellow
error_symbol = '[❯](fg:#ea6962 bold)' # gruvbox red
vicmd_symbol = '[❮](fg:#111313 bold)'

[git_branch]
style = "fg:#d8a657 bold" # gruvbox yellow
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#ea6962)]($style)'

[os]
format = "[$symbol]($style)"
style = "fg:#7daea3 bold" # gruvbox blue
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

[line_break]
disabled = true
