# Symphony by vyrx / Theme: Aamis / https://github.com/vyrx-dev
# : Manager [[[

[mgr]
cwd = { fg = "#eadccc" }

# Tab
tab_active = { fg = "#0f0f0f", bg = "#cea37f", bold = true }
tab_inactive = { fg = "#a08876", bg = "#1a1816" }
tab_width = 1

# Find
find_keyword = { fg = "#e8ab3b", bold = true, italic = true, underline = true }
find_position = { fg = "#e8ab3b", bold = true, italic = true }

# Marker
marker_copied = { fg = "#e2be8a", bg = "#e2be8a" }
marker_cut = { fg = "#eacea7", bg = "#eacea7" }
marker_marked = { fg = "#e8ab3b", bg = "#e8ab3b" }
marker_selected = { fg = "#cea37f", bg = "#cea37f" }

# Count
count_copied = { fg = "#0f0f0f", bg = "#eacea7" }
count_cut = { fg = "#0f0f0f", bg = "#eacea7" }
count_selected = { fg = "#0f0f0f", bg = "#cea37f" }

# Border
border_symbol = " "
border_style  = { fg = "#cea37f" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#1a1816", fg = "#706a6a" }

[mode]
# Mode
normal_main = { bg = "#cea37f", fg = "#0f0f0f", bold = true }
normal_alt  = { bg = "#252220", fg = "#a08876" }

# Select mode
select_main = { bg = "#e8ab3b", fg = "#0f0f0f", bold = true }
select_alt  = { bg = "#252220", fg = "#a08876" }

# Unset mode
unset_main = { bg = "#f4bb54", fg = "#0f0f0f", bold = true }
unset_alt  = { bg = "#252220", fg = "#a08876" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#cea37f", bg = "#252220" }
progress_error = { fg = "#e25d6c", bg = "#252220" }

# Permissions
permissions_t = { fg = "#e2be8a" }
permissions_w = { fg = "#f4bb54" }
permissions_x = { fg = "#e25d6c" }
permissions_r = { fg = "#cea37f" }
permissions_s = { fg = "#e8ab3b" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#cea37f" }
active = { fg = "#e8ab3b", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#cea37f" }
value = { fg = "#eadccc" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#cea37f", bold = true, bg = "#0f0f0f" }
inactive = { fg = "#706a6a", bg = "#0f0f0f" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#cea37f", bg = "#1a1816" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#cea37f" }
title = {}
hovered = { fg = "#e8ab3b", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#252220" }
cand = { fg = "#cea37f" }
rest = { fg = "#706a6a" }
desc = { fg = "#eadccc" }
separator = " ‚ñ∂ "
separator_style = { fg = "#eadccc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eadccc" }
run = { fg = "#eadccc" }
footer = { fg = "#0f0f0f", bg = "#e2be8a" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e8ab3b" }
title_warn = { fg = "#f4bb54" }
title_error = { fg = "#e25d6c" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#e2be8a" },

    # Media
    { mime = "{audio,video}/*", fg = "#f4bb54" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ede4c8" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#cea37f" },

    # Special files
    { name = "*", is = "orphan", bg = "#3a0a0a" },
    { name = "*", is = "exec", fg = "#e8ab3b" },

    # Fallback
    { name = "*", fg = "#eadccc" },
    { name = "*/", fg = "#cea37f" },
]

# : ]]]
